In [1]:
import os

print(os.getcwd())

C:\Teju\customer_churn_ML_model\notebooks

In [2]:
print(os.listdir())

['.ipynb_checkpoints', 'Untitled.ipynb']

In [3]:
import os

print(os.listdir("../data"))

['.ipynb_checkpoints', 'customer_churn.csv']

In [1]:
import pandas as pd

df = pd.read_csv("../data/customer_churn.csv")

df.head()

  CustomerID  Age  Tenure  MonthlyBill  SupportCalls Churn
0       C001   25      12         1500             1    No
1       C002   42       4         3200             5   Yes
2       C003   31      24         1800             2    No
3       C004   50       3         4000             7   Yes
4       C005   28      18         2100             2    No

In [2]:
%pip install pandas numpy scikit-learn joblib matplotlib seaborn

Requirement already satisfied: pandas in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (3.0.2)
Requirement already satisfied: numpy in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (2.4.4)
Requirement already satisfied: scikit-learn in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (1.8.0)
Requirement already satisfied: joblib in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (1.4.2)
Requirement already satisfied: matplotlib in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (3.11.0)
Requirement already satisfied: seaborn in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=9 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\saite\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import numpy as np
import sklearn
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

print("All packages imported successfully!")
print("Joblib version:", joblib.__version__)
print("Scikit-learn version:", sklearn.__version__)

All packages imported successfully!
Joblib version: 1.4.2
Scikit-learn version: 1.8.0

In [5]:
data_path = "../data/customer_churn.csv"
df = pd.read_csv(data_path)
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [8]:
df.head()

  CustomerID  Age  Tenure  MonthlyBill  SupportCalls Churn
0       C001   25      12         1500             1    No
1       C002   42       4         3200             5   Yes
2       C003   31      24         1800             2    No
3       C004   50       3         4000             7   Yes
4       C005   28      18         2100             2    No

In [9]:
df.shape

(50, 6)

In [10]:
df.columns

Index(['CustomerID', 'Age', 'Tenure', 'MonthlyBill', 'SupportCalls', 'Churn'], dtype='str')

In [11]:
df.info

<bound method DataFrame.info of    CustomerID  Age  Tenure  MonthlyBill  SupportCalls Churn
0        C001   25      12         1500             1    No
1        C002   42       4         3200             5   Yes
2        C003   31      24         1800             2    No
3        C004   50       3         4000             7   Yes
4        C005   28      18         2100             2    No
5        C006   45       6         3500             6   Yes
6        C007   36      30         1900             1    No
7        C008   52       2         4500             8   Yes
8        C009   29      15         2200             3    No
9        C010   41       5         3800             6   Yes
10       C011   33      20         2000             2    No
11       C012   48       7         3300             5   Yes
12       C013   26      25         1700             1    No
13       C014   55       1         5000             9   Yes
14       C015   39      22         2300             2    No
15       C016   44       8         3600             5   Yes
16       C017   30      19         1900             2    No
17       C018   51       4         4200             7   Yes
18       C019   34      27         1800             1    No
19       C020   47       6         3900             6   Yes
20       C021   27      14         1600             1    No
21       C022   43       5         3400             5   Yes
22       C023   32      21         2100             2    No
23       C024   49       3         4100             7   Yes
24       C025   35      26         2000             1    No
25       C026   46       7         3700             6   Yes
26       C027   29      17         1900             2    No
27       C028   54       2         4800             8   Yes
28       C029   38      23         2200             2    No
29       C030   42       5         3500             5   Yes
30       C031   24      16         1500             1    No
31       C032   50       4         4300             7   Yes
32       C033   37      28         2100             2    No
33       C034   45       6         3600             6   Yes
34       C035   31      18         1800             2    No
35       C036   53       3         4700             8   Yes
36       C037   40      25         2300             2    No
37       C038   48       5         3900             6   Yes
38       C039   28      20         1700             1    No
39       C040   44       4         3500             5   Yes
40       C041   33      29         2000             1    No
41       C042   52       6         4400             7   Yes
42       C043   26      13         1600             2    No
43       C044   47       3         4000             6   Yes
44       C045   36      24         2100             2    No
45       C046   51       5         4200             7   Yes
46       C047   30      18         1800             1    No
47       C048   43       7         3700             5   Yes
48       C049   34      22         1900             2    No
49       C050   49       4         4100             6   Yes>

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
# Understand the Target Variable
df["Churn"].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [14]:
features = [
    "Age",
    "Tenure",
    "MonthlyBill",
    "SupportCalls"
]
target = "Churn"
X = df[features]  #  return  only given columns values 
Y = df[target]     # return only churn column values 
print( X.head() )
print( Y.head() )

   Age  Tenure  MonthlyBill  SupportCalls
0   25      12         1500             1
1   42       4         3200             5
2   31      24         1800             2
3   50       3         4000             7
4   28      18         2100             2
0     No
1    Yes
2     No
3    Yes
4     No
Name: Churn, dtype: str

In [16]:
display(Y.head())

0     No
1    Yes
2     No
3    Yes
4     No
Name: Churn, dtype: str

In [19]:
# Split Data -  training data (learning) and test data (evaluate)
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42,
    stratify=Y
)
print("Total records :", len(X))
print("Training data :", len(X_train))
print("Testing data  :", len(X_test))

Total records : 50
Training data : 40
Testing data  : 10

In [25]:
# scale the feature 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
# Create the ML Model
model = LogisticRegression(
    random_state=42
)

In [27]:
# train the model
model.fit(
    X_train_scaled,
    Y_train
)
print("Model training completed!")

Model training completed!

In [28]:
# Make Predictions
Y_pred = model.predict(
    X_test_scaled
)
print("Predictions:")
print(Y_pred)

Predictions:
['No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes']

In [30]:
# compare actual vs predicted
comparison = pd.DataFrame({
    "Actual": Y_test.values,
    "Predicted": Y_pred
})
comparison

  Actual Predicted
0     No        No
1     No        No
2     No        No
3     No        No
4    Yes       Yes
5    Yes       Yes
6    Yes       Yes
7    Yes       Yes
8     No        No
9    Yes       Yes

In [31]:
import joblib
#Save the Trained Model
model_path = "../models/churn_model.pkl"
joblib.dump(
    model,
    model_path
)
print("Model saved successfully!")

Model saved successfully!

In [32]:
# save the scalar
scaler_path = "../models/scaler.pkl"
joblib.dump(
    scaler,
    scaler_path
)
print("Scaler saved successfully!")

Scaler saved successfully!

In [33]:
# load  the model 
loaded_model = joblib.load(
    "../models/churn_model.pkl"
)
loaded_scaler = joblib.load(
    "../models/scaler.pkl"
)
print("Model and scaler loaded successfully!")

Model and scaler loaded successfully!

In [34]:
#  New Customer Prediction
# load the new customer
new_customer = pd.DataFrame([
    {
        "Age": 45,
        "Tenure": 5,
        "MonthlyBill": 3500,
        "SupportCalls": 6
    }
])
new_customer

   Age  Tenure  MonthlyBill  SupportCalls
0   45       5         3500             6

In [37]:
# The model was trained using scaled data. 
# So we must scale the new customer's data using the same saved scaler.
new_customer_scaled = loaded_scaler.transform(
    new_customer
)
prediction = loaded_model.predict(
    new_customer_scaled
)
print("Prediction:", prediction)

Prediction: ['Yes']

In [36]:
if prediction[0] == 1:
    print("Customer is likely to LEAVE (CHURN).")
else:
    print("Customer is likely to STAY.")

Customer is likely to STAY.